POST http://localhost:3000/Books
Content-Type: application/json

{
    "book_Name":"Twilight",
    "book_Author":"abc xyz",
    "book_Genre":["Action","Thriller","Fiction","Romantic"]
}

###

POST http://localhost:3000/Books
Content-Type: application/json

{
    "book_Name":"Twisted Love",
    "book_Author":"xyz abc",
    "book_Genre":["Romantic","Tragedy"]
}
###

POST http://localhost:3000/Books
Content-Type: application/json

{
    "book_Name":"Rich Dad Poor Dad",
    "book_Author":"abc def",
    "book_Genre":["Finances"]
}
###

POST http://localhost:3000/Books
Content-Type: application/json

{
    "book_Name":"Twisted Love",
    "book_Genre":["Romantic","Tragedy"]
}

###

GET http://localhost:3000/Books

###

GET http://localhost:3000/Books/genre?book_Genre=Romantic

###

GET http://localhost:3000/Books/64dd01c381242b358ce72afa